### ISSUE TITLE
Problem using sliff:g tag, %s appears in default text in textview

### ISSUE THREAD

**Issue by devayush20** [udacity/Just-Java#14]
app/src/main/res/values/strings.xml
I used the xliff:g tag in my code, but the **%s** appears in the default text, when I open the app.
It disappears once I enter text in the EditText View. Also, it does not appear in the orderSummary in Gmail.

<string name="order_summary_name">Name: <xliff:g id="name" example="Amy">%s</xliff:g></string>

I am attaching screenshots-
![image](https://user-images.githubusercontent.com/78680067/149410799-b60cc08c-fbbe-4415-8924-b3c2b86ee277.png)

![image](https://user-images.githubusercontent.com/78680067/149410762-a9643762-4f21-4426-a1a5-c077f5e26e4a.png)

![image](https://user-images.githubusercontent.com/78680067/149410701-ea6fcb0b-fd55-4170-8b87-13711a6baa03.png)

Can somebody help me with this?

**Comment by SudKul** [comment]
Hi @devayush20 
Use the https://knowledge.udacity.com/ platform to discuss individual issues.
